### PR TITLE
Wrap email-status request in client token, if needed

### PR DESCRIPTION
**Pull request by audungk**
Since email-status requires a client token, I thought it was better if this was left to the SDK, and not the implementation

### CODE REVIEW

**Comment by joawan** [comment]
Cool! Do you have any suggestion on who could review this PR? @mikaoj perhaps?

**Comment by audungk** [comment]
@joawan: I don't know who inside Schibsted who has access, so but @mikaoj has been so kind to review my previous requests

**Comment by mikaoj** [comment]
I'll take a look at it tomorrow :)

**Comment by mikaoj** [comment]
Long time no see, @audungk 🤓

I would probably prefer if all requests behaved the same way, and the others ones which require an access token lack this functionality.

And it looks like it could have the side effect of signing a user out, not sure if I like that but at the very least it should be documented.

**Comment by audungk** [comment]
@joawan: Is it possible to get a list of requests that actually require a client token? I remember you saying something about the documentation not beeing up to date.

@mikaoj: For email-status, that side-effect would probably be accepted, since you only require email status for login/signup?

**Comment by audungk** [comment]
Picking up this after returning from paternety leave. 

I've looked over the SPiDClient, and those requests requiring a token, are requests that are made when logged in, thus replacing the need for a client token. Checking email availability is from what I can see the only request that can/will be made from a non-authenticated state, thus needing the check for an accessToken. 

In terms of documentation, I havent found the parts logging you out unintentionally, so I've not added documentation. 

Also, 2.4 does not build with carthage, so I took the liberty of moving SPIDAgreements.h to the public headers

**Comment by mikaoj** [comment]
Great 🎂, I'll take a look later this week!

**Comment by mikaoj** [comment]
The diff feels strange as it contains changes that other people has done and that already are in master.
Could you apply some git voodoo and fix that? :)

**Comment by audungk** [comment]
See #41 for voodoo

**Comment by mikaoj** [comment]
Perfect, I'll close this one

**Pull request closed without merging**
