### PR TITLE
Enable building frameworks

### PR DESCRIPTION
**Pull request by audungk**
For SPiD to be used with Carthage, the project needs a shared framework scheme. This pull requests adds a framework-target, and fixes two deprecated warnings related to percent-escapes.

### CODE REVIEW

**Comment by mikaoj** [comment]
Great! I'll have a look at it later this week.

In the meantime there are some conflicts for you to resolve 👻

**Comment by audungk** [comment]
👍

**Comment by mikaoj** [comment]
There are a couple of things:
* The travis build is broken.
* I don't think we want to have Carthage/Build folder under version control.
* Lots of files in the diff is just adding a space, putting { on a separate line. Did you apply some automated code formatter?

* Would it be possible to add a test to verify that URLQueryPartAllowedCharacterSet/urlEncodeString works as intended? _I know that there aren't any tests yet, but you have to start somewhere_
* Could you add a Carthage badge to the README? _Yeapp, the README isn't much to look at right now, but I'm hoping to remedy that_

**Comment by audungk** [comment]
Yeah, I use clang-format on save. Helps me keep readable code without thinking too much on it...

Also, I fixed the things requested, plus I took the liberty of renaming the urlEncodeString, since the reserved characters would cause errors if it was used with complete URL-strings, and not key/value-parts as the current usage of the code. I think it at least makes sense for the static-lib, since SPiDUtils can be imported by anyone, but it could be made a project-header for the framework...

**Comment by mikaoj** [comment]
Thanks for bearing with me! 😉

Perhaps I'm nitpicking now, but would you mind reverting the code formatting stuff?
* It keeps the size of the PR down - easier to review.
* It keeps the style consistent between all files.

**Comment by audungk** [comment]
Done!

**Comment by mikaoj** [comment]
I haven't forgotten about this, will look into it sometime this week.

**Comment by mikaoj** [comment]
Alright, so I have checked out your branch and looked over it now.
Is there any reason for why we would want a static library (SPiDSDK) and a framework (SPiD)?

If not:
* Delete the old static library
* Rename framework to SPiDSDK
* Make sure that the example apps links against the SPiDSDK framework

After that I would be happy to merge your PR 😃

**Comment by audungk** [comment]
Well, since I don't administer the SDK, I made them as alternatives, alongside each other. I must admit, I cannot think of any answer to why you would both a framework and a static lib, so I'll be more than happy to delete the static lib!

(Just need to complete some work-stuff first...)

**Comment by mikaoj** [comment]
I can't think of any either, so happy times! 🍾

**Comment by mikaoj** [comment]
I had som free time, so I went ahead and made above mentioned changes and opened #30.

**Pull request closed without merging**
