### PR TITLE
Replace deprecated NSURLConnection with NSURLSession

### PR DESCRIPTION
**Pull request by mikaoj**
NSURLConnection has been deprecated by apple (and can't be used on apple watch/tv) so this PR replaces it with NSURLSession.

* Replaced NSURLConnection with NSURLSession.
* Bumped version number to 2.0.0 (as there are some breaking changes).
* Bumped deployment targets to iOS 7.0 (NSURLSession requires it).
* Removed the SPiDError class and moved it's functionality to a category
* Fixed a memory leak
* A bunch of small fixes/cleanup

There are some breaking changes:
* A couple of method names where renamed (had ugly java-style naming).
* Callbacks happen on a background thread, it should be up to the user of this SDK to decide if the callback needs to do stuff on main (UI) not the SDK itself (And if I read the code correctly, it was even executing the requests on main before).

### CODE REVIEW

**Comment by eriksundin** [comment]
+1

**Comment by tommysafstrom** [comment]
:+1:

**Comment by mikaoj** [comment]
Day 31: They still don't suspect I am a pull request

**Comment by oskarh** [comment]
Thanks for the pull request!

No one with clear ownership of this repository unfortunately so not the swiftest replies here. Sorry for the delay.

**Pull request merged**
