### PR TITLE
Fix issue with parameterless blocks

### PR DESCRIPTION
**Pull request by audungk**

### CODE REVIEW

**Comment by mikaoj** [comment]
Nice, you turned on a bunch of warnings...now you get to fix those! ;)

Other then that I see no problems with mergins this, but out of curiosity what issues did parameterless block cause? :)

**Comment by audungk** [comment]
No issues, but it is the equivalent of writing blocks with `(^(*))`, which can lead to potential evil nasty bugs.

**Comment by audungk** [comment]
Followup: I don't get these messages, but could that be because there is a different version of Xcode on Travis?

**Comment by 3lvis** [comment]
Issues handled here https://github.com/schibsted/sdk-ios/pull/44 

Closing.

**Pull request closed without merging**
