### PR TITLE
Added nullability for Swift compatibility

### PR DESCRIPTION
**Pull request by ikovalisko**
Hi!
I'm using SDK in Swift project and found it difficult to work with completion handlers as they all return error implicitly unwrapped `NSError!`. 

Of course, I could stay with `error!=nil`, but that's not what is Swift for :) So, I went through classes I'm using and added `nullable` annotations. Hence, that those classes are wrapped with `*ASSUME_NONULL` macros.

Please, let me know what you think about this work and where I should add nullability. Not sure it's needed for all headers, though.

### CODE REVIEW

**Comment by ikovalisko** [comment]
Alright, I see few nullability-related issues in Travis log. Will look into it later.

**Comment by mikaoj** [comment]
Nullability annotations would be nice, keep it up! :)

**Comment by ikovalisko** [comment]
CI seems passing now. @mikaoj, please have a look!

**Comment by mikaoj** [comment]
If you run analyze on the sdk it will find a couple of places where we return nil from an method that is expected to return a non-null value

**Comment by ikovalisko** [comment]
Fixed those warnings

**Comment by mikaoj** [comment]
Great, thanks! :)

**Comment by ikovalisko** [comment]
Btw, when do you plan to release new version?

**Comment by mikaoj** [comment]
Don't know...contemplating if this is enough to warrant a new release...

**Comment by ikovalisko** [comment]
No hassle from me. I may keep using HEAD :)

**Comment by mikaoj** [comment]
I pushed 2.3.2 with your Nullability annotations :)

**Pull request merged**
